
package org.signserver.adminws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-11-22T12:25:20.148+07:00
 * Generated source version: 3.5.4
 */

@WebFault(name = "AuthorizationDeniedException", targetNamespace = "http://adminws.signserver.org/")
public class AuthorizationDeniedException_Exception extends Exception {

    private org.signserver.adminws.AuthorizationDeniedException faultInfo;

    public AuthorizationDeniedException_Exception() {
        super();
    }

    public AuthorizationDeniedException_Exception(String message) {
        super(message);
    }

    public AuthorizationDeniedException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthorizationDeniedException_Exception(String message, org.signserver.adminws.AuthorizationDeniedException authorizationDeniedException) {
        super(message);
        this.faultInfo = authorizationDeniedException;
    }

    public AuthorizationDeniedException_Exception(String message, org.signserver.adminws.AuthorizationDeniedException authorizationDeniedException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = authorizationDeniedException;
    }

    public org.signserver.adminws.AuthorizationDeniedException getFaultInfo() {
        return this.faultInfo;
    }
}
