
package org.signserver.adminws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-11-22T12:25:20.165+07:00
 * Generated source version: 3.5.4
 */

@WebFault(name = "IllegalRequestException", targetNamespace = "http://adminws.signserver.org/")
public class IllegalRequestException_Exception extends Exception {

    private org.signserver.adminws.IllegalRequestException faultInfo;

    public IllegalRequestException_Exception() {
        super();
    }

    public IllegalRequestException_Exception(String message) {
        super(message);
    }

    public IllegalRequestException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IllegalRequestException_Exception(String message, org.signserver.adminws.IllegalRequestException illegalRequestException) {
        super(message);
        this.faultInfo = illegalRequestException;
    }

    public IllegalRequestException_Exception(String message, org.signserver.adminws.IllegalRequestException illegalRequestException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = illegalRequestException;
    }

    public org.signserver.adminws.IllegalRequestException getFaultInfo() {
        return this.faultInfo;
    }
}
