
package org.signserver.adminws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.4
 * 2023-02-14T14:53:03.617+07:00
 * Generated source version: 3.5.4
 */

@WebFault(name = "InvalidWorkerIdException", targetNamespace = "http://adminws.signserver.org/")
public class InvalidWorkerIdException_Exception extends Exception {

    private org.signserver.adminws.InvalidWorkerIdException faultInfo;

    public InvalidWorkerIdException_Exception() {
        super();
    }

    public InvalidWorkerIdException_Exception(String message) {
        super(message);
    }

    public InvalidWorkerIdException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidWorkerIdException_Exception(String message, org.signserver.adminws.InvalidWorkerIdException invalidWorkerIdException) {
        super(message);
        this.faultInfo = invalidWorkerIdException;
    }

    public InvalidWorkerIdException_Exception(String message, org.signserver.adminws.InvalidWorkerIdException invalidWorkerIdException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidWorkerIdException;
    }

    public org.signserver.adminws.InvalidWorkerIdException getFaultInfo() {
        return this.faultInfo;
    }
}
