
package org.signserver.adminws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.4
 * 2023-02-14T14:53:03.848+07:00
 * Generated source version: 3.5.4
 */

@WebFault(name = "QueryException", targetNamespace = "http://adminws.signserver.org/")
public class QueryException_Exception extends Exception {

    private org.signserver.adminws.QueryException faultInfo;

    public QueryException_Exception() {
        super();
    }

    public QueryException_Exception(String message) {
        super(message);
    }

    public QueryException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public QueryException_Exception(String message, org.signserver.adminws.QueryException queryException) {
        super(message);
        this.faultInfo = queryException;
    }

    public QueryException_Exception(String message, org.signserver.adminws.QueryException queryException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = queryException;
    }

    public org.signserver.adminws.QueryException getFaultInfo() {
        return this.faultInfo;
    }
}
