
package org.signserver.adminws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.4
 * 2022-11-22T12:25:20.212+07:00
 * Generated source version: 3.5.4
 */

@WebFault(name = "ResyncException", targetNamespace = "http://adminws.signserver.org/")
public class ResyncException_Exception extends Exception {

    private org.signserver.adminws.ResyncException faultInfo;

    public ResyncException_Exception() {
        super();
    }

    public ResyncException_Exception(String message) {
        super(message);
    }

    public ResyncException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ResyncException_Exception(String message, org.signserver.adminws.ResyncException resyncException) {
        super(message);
        this.faultInfo = resyncException;
    }

    public ResyncException_Exception(String message, org.signserver.adminws.ResyncException resyncException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = resyncException;
    }

    public org.signserver.adminws.ResyncException getFaultInfo() {
        return this.faultInfo;
    }
}
